### ISSUE TITLE
Control minimum file size

### ISSUE THREAD

**Issue by pauldreik** [pauldreik/rdfind#1]
Sometimes it is of interest to ignore small files. rdfind already ignores empty files by default. The suggestion is to replace the -ignoreempty flag (or complement it) with a -minsize N flag where N is the minimum size in bytes. Using N=0 would mean empty files are included. 

This is an old issue, reported by Andrew Buehler 20131130.

**Comment by thomas-mc-work** [comment]
Also it would be great to have a sensible default of e.g. 0.5 MB. This would likely speed up every execution a lot.

**Comment by pauldreik** [comment]
This is now implemented. The default is 1 byte, because -minsize1 is a synonym to -ignoreempty true, which is already the default.
There is a pretty obvious possible optimization to handling small files which are to be ignored: carrying out the check earlier, before they are added to the list of files to be investigated. Perhaps I will try to fix that as well...

**Comment by thomas-mc-work** [comment]
I think this is worth a release, maybe `1.4`.

**Comment by pauldreik** [comment]
Yep, that is the plan. I have some other changes as well which are almost finished.

**Comment by pauldreik** [comment]
This is now in https://github.com/pauldreik/rdfind/releases/tag/releases%2F1.4.0-alpha0 Would you mind giving it a go, @thomas-mc-work ?
Thanks.

**Comment by thomas-mc-work** [comment]
I'll test it this week.

**Comment by thomas-mc-work** [comment]
Excuse me for the delay. I've tested this now and it's working gracefully.

Optionally it'd be lovely to have short notations for kilo/mega bytes like `4M` or `10K`.

Thank you for this feature!
