### ISSUE TITLE
Convert options to getopts standandard

### ISSUE THREAD

**Issue by awiebe** [pauldreik/rdfind#16]
There might be no way to do it without breaking backwards compatibility, but specifying options to rdfind is really strange as currently implemented.

Long options should really be specified as
`rdfind --makehardlinks <path>`
instead of
`rdfind -makehardlinks true <path>`

To be consistent with other command line tool invocations.

**Comment by pauldreik** [comment]
Hi,
I agree the syntax is awkvard, I think I just mimicked some other command I used at the time. It has crossed my mind to change the options to the more well recognized syntax. However I made a decision to keep it, in order not to risk confusion and backwards compatibility. I believe that was the right choice.
