### ISSUE TITLE
Whats the progress?

### ISSUE THREAD

**Issue by GronbergInfo** [pauldreik/rdfind#163]
I started a rdfind almsot 10 hours ago.
It has checked all 215k files from first bytes and last bytes and now calculating sha1 for each file.

Wish there was a progress information stating how many it has done, and how many to go.
Right now i dont know if its 2 minutes more or 2 weeks.

My server has CPU: AMD Ryzen 7 7700X (16) @ 4.500GHz
and utilization is only 8%.

I know there should be atleast 25-30% dupes (comparing server vs an external usb 3 drive)

**Comment by valerio-bozzolan** [comment]
Thanks for reporting. If I understand correctly, you can follow this issue instead:

https://github.com/pauldreik/rdfind/issues/30

See you there

(Evaluate the closing of this #163 if you agree)

**Comment by GronbergInfo** [comment]
> Thanks for reporting. If I understand correctly, you can follow this issue instead:
> 
> #30
> 
> See you there
> 
> (Evaluate the closing of this #163 if you agree)

Seems like it.

**Comment by valerio-bozzolan** [comment]
OK :) Feel free to close this, to follow #163 :+1:
