### ISSUE TITLE
autotools macro issue

### ISSUE THREAD

**Issue by alexispaz** [pauldreik/rdfind#19]
When running `autoreconf -fi` and then `./configure` I get the following error
```
./configure: line 4176: syntax error near unexpected token `11,noext,mandatory'
./configure: line 4176: `      AX_CXX_COMPILE_STDCXX(11,noext,mandatory)'
```
Probably the macro is missing? Creating a local m4 folder might help?

**Comment by pauldreik** [comment]
I think this happens with either old systems (like Ubuntu 14.04), or (from the top of my head) if the autotools-archive package is missing. What system are you on?

**Comment by alexispaz** [comment]
My apologies, the error is at the time of `./configure` not `autoreconf -fi`. I just edited and corrected the question. My system is openSUSE 42.2 (x86_64) and using GNU Autoconf 2.69.

**Comment by djhejna** [comment]
I am seeing the same macro issue on 64-bit Ubuntu 14.04 and Ubuntu 18.04. Lacking further details in the INSTALL file, after cloning in git, I run:
./bootstrap.sh  (errors: aclocal not found)
autoconf
configure.ac:11: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

 ./bootstrap.sh 
configure.ac:11: installing './install-sh'
configure.ac:11: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
it seems like everything went fine. now try
./configure && make

./configure
....
checking for _FILE_OFFSET_BITS value needed for large files... no
./configure: line 4230: syntax error near unexpected token `11,noext,mandatory'
./configure: line 4230: `      AX_CXX_COMPILE_STDCXX(11,noext,mandatory)'

which originate from line 73/74 from configure.ac

**Comment by pauldreik** [comment]
I tested this with a fresh clone on ubuntu 18.04. It works for me (most likely because I have everything installed).
./bootstrap.sh gave you an error message, "aclocal not found". Install it (apt install automake), and see if it works better.

**Comment by djhejna** [comment]
Yes, after installing and running autoconf, ./bootstrap.sh finishes with no errors.  It's the AX_CXX macro that is difficult to know how to fix.  (What needs to be installed?)

**Comment by pauldreik** [comment]
I have autoconf-archive installed: apt install autoconf-archive

**Comment by djhejna** [comment]
That's the ticket:  apt install autoconf-archive and then rerunning autoconf, and then ./configure produces makefile.  Thank you so much for the prompt responses!

**Comment by pauldreik** [comment]
Good! It seems like the INSTALL or even the readme.md could be improved on this point. Or perhaps also the bootstrap.sh script, since that could suggest what to do after it fails autoconf. Would you like to do a pull request?

**Comment by djhejna** [comment]
Yes, happy to do that!  I am working on a minor enhancement to the overall program the adds some functionality I have found useful. Will incorporate those changes as well and submit pull request for you review and comment on in a couple of days.  Best wishes.

**Comment by pauldreik** [comment]
Sounds nice but please keep the pull requests separate. I am unlikely to accept stuff that complicates things (correctness and stability are now the primary goals of rdfind).

**Comment by djhejna** [comment]
OK will do.  What is the best way to detail the changes and discuss why these are extremely low-risk changes? I am happy to chat interactively here (different thread) or elsewhere.  Or you can walk the code changes.

**Comment by pauldreik** [comment]
The best thing is to file an issue here about the problem you try to solve, and we will continue the discussion there. It is good for others to see, in case they independently gets the same idea.

**Comment by pauldreik** [comment]
fixed in https://github.com/pauldreik/rdfind/commit/0fffab7dd90d4d4afea110f0a1a60313ff74f0b9
