### ISSUE TITLE
Nettle issues on centos

### ISSUE THREAD

**Issue by rayfoss** [pauldreik/rdfind#21]
I'm trying to build this on centos 7 with autotools. I have an old version of rdfind with yum.

```
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking nettle/sha.h usability... no
checking nettle/sha.h presence... no
checking for nettle/sha.h... no
configure: error:
 nettle header files missing. Please install nettle
 first. If you have already done so and get this error message
 anyway, it may be installed somewhere else, maybe because you
 don't have root access. Pass CPPFLAGS=-I/your/path/to/nettle to configure
 and try again. The path should be so that #include "nettle/sha.h" works.
 On Debian-ish systems, use "apt-get install nettle-dev" to get a system
 wide nettle install.
```

I tried the pass `CPPFLAGS=-I"/opt/rfind/nettle" ./configure` ... no cigar. sha.h is there and nettle seemed to build correctly.

**Comment by madongge** [comment]
`yum remove epel-release`
// first  remove epel-release 
`wget https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm`
// then download  epel-release
`rmp -Uvh epel-release-7-11.noarch.rpm`
//and install  epel-release-7-11.noarch.rpm
`yum insatll refind -y`
// install redfind   
// CentOS Linux release 7.6.1810 (Core)

**Comment by rayfoss** [comment]
You can install the repo under another name and disable it, the. Tell yum to use it. That way you don't affect the rest of the system. Thx!
