### ISSUE TITLE
Prefer base filenames, older files to asciibetical listing

### ISSUE THREAD

**Issue by reikoNeko** [pauldreik/rdfind#22]
While using rdfind to clean up my ebooks, the tool deleted copies that were downloaded first in favor of those that had a (1).ext in the filename, an artifact of downloading files twice in Firefox.

In the -deleteduplicates process, dropping files that have already been tagged by another program as potential dupes should be preferable.

DUPTYPE_FIRST_OCCURRENCE 69 0 6487394 64769 29229369 3 eBooks/9781787123687(1).epub
DUPTYPE_WITHIN_SAME_TREE -69 0 6487394 64769 29230708 3 eBooks/9781787123687(2).epub
DUPTYPE_WITHIN_SAME_TREE -69 0 6487394 64769 29231261 3 eBooks/9781787123687.epub
DUPTYPE_FIRST_OCCURRENCE 310 0 7356520 64769 28967090 3 eBooks/gamehacking(1).pdf
DUPTYPE_WITHIN_SAME_TREE -310 0 7356520 64769 25559164 3 eBooks/gamehacking.pdf
DUPTYPE_FIRST_OCCURRENCE 28 0 7367823 64769 33296269 3 eBooks/9781783553358-PYTHON_DATA_ANALYSIS(1).pdf
DUPTYPE_WITHIN_SAME_TREE -28 0 7367823 64769 33296270 3 eBooks/9781783553358-PYTHON_DATA_ANALYSIS.pdf

**Comment by pauldreik** [comment]
I interpret this as this would be a rule that goes in when both the position on the command line and depth are equal, right?
And the rule would be (horrible pseudo code):
Given two files $filename$ext and $filename$pat$ext, where $pat matches (X), sort $filename$ext first.
This does not sound trivial to get right. I am reluctant to introducing something like that. But I've been wrong before. May I suggest that you tweak the sources a bit to see if you can get what you want? Specifically, I think there is where it should go: https://github.com/pauldreik/rdfind/blob/909e90f974ec1248fce6be71e71722e559745445/Rdutil.cc#L292

**Comment by reikoNeko** [comment]
I plan to do that later this week after I've had time to go through it. In the meantime, the following will work after a dry run:

awk '/\(1\)/ {print $8}' results.txt | xargs rm
