### ISSUE TITLE
Support filtering by file size to allow parallelization of workloads and smaller job sizes

### ISSUE THREAD

**Issue by djhejna** [pauldreik/rdfind#23]
Support for min and max filesizes to allow for “file size based partitioning” of the deduplication process.  One could think of this as “banding” along the spectrum of sizes or sharding.  

## Why this enhancement is safe:
The size filtering only affects whether or not files are pushed onto the queue to be worked on.  It is merely a “cull” of the files that are walked in the directory tree..

## Why this enhancement is needed:
We work on several machine learning and deep learning projects which operate on millions of files. Deduplication is critical in certain applications and categorizations.  However running rdfind on the entire dataset can lead to jobs that do not finish before the arrival of new data and the performance degrades as the working set grows beyond physical memory.  By partitioning on file size, the deduplication operation can be run in parallel (machines and cores) and in smaller batches with no loss of functionality and gains in speed from parallelization.  Additionally, since certain size files are more frequent in our applications, it is possible to target deduplication to “the most active file sizes” in the archives.

## Other motivations:
I have used this feature for some years and it is valuable to me.  I think they would be useful to others.  There is no discernible impact on runtime performance.  Arguments that running in parallel is fraught with danger only apply if running in parallel over the same size band which is no different than running two rdfind jobs at once. (This by the way happens when using cron and discovering a prior job has not finished, so partitioning to faster smaller jobs is actually safer in my mind.)

**Comment by pauldreik** [comment]
I understand the use case and I like the idea.

**Comment by pauldreik** [comment]
I implemented this, now waiting for the appveyour servers [to become healthy again](https://ci.appveyor.com/project/pauldreik/rdfind/builds/24693772). [Travis seems to pass](https://travis-ci.org/pauldreik/rdfind/builds/535205955). See https://github.com/pauldreik/rdfind/pull/26

**Comment by djhejna** [comment]
I'm delighted to hear that, thanks for implementing this!
Don
