### ISSUE TITLE
rdfind creating symlinks and midnight commander

### ISSUE THREAD

**Issue by 8ohmh** [pauldreik/rdfind#25]
Hi, 
there's is a "problem" with rdfind, creating symlinks and midnight commander. If rdfind is creating a symlink for a duplicate file in the same path, midnight commander IS NOT showing both of them,  but only either the symlink OR the real file. OK, by 
`find <path> -type l -print `
The symlinks can be sorted out but this is problematic. How to circumvent that? Check wether symlink should only be created in a new directory (e.g. 000-symlinks in that folder?)

**Comment by pauldreik** [comment]
I think this is more a problem in midnight commander than rdfind?
rdfind replaces filenames with a symlink, which is the advertised behaviour.
If I ever get around to do a user-supplied callback, this could be handled by those who want it.
