### ISSUE TITLE
tell rdfind to store results.txt in a different location

### ISSUE THREAD

**Issue by babbahotep** [pauldreik/rdfind#34]
Hi,

not sure if I am doing it right but If I tell rdfind to scan folders with spaces it fails.

admin@VMX-Mate-finddupes:~$ rdfind -n true /mnt/nas/Adults/TV\ Shows
(DRYRUN MODE) Now scanning "/mnt/nas/Adults/TV Shows", found 0 files.
(DRYRUN MODE) Now have 0 files in total.
(DRYRUN MODE) Removed 0 files due to nonunique device and inode.

if I start rdfind in the dir with rdfind ./ it works but then it cant write the results.txt

Is there an option with -outputname to have the results.txt written to a different location eg ~/results.txt?

thanks
chris

**Comment by pauldreik** [comment]
Does ```rdfind -oiutputname ~/results.txt dir``` solve your problem?
