### ISSUE TITLE
[feature request] different treatment of directories?

### ISSUE THREAD

**Issue by TBeholder** [pauldreik/rdfind#4]
Right now "**rdfind** … **-makesymlinks**|**-deleteduplicates true** … **/directory1/ /directory2/**" will attempt to prune duplicates in both. Sometimes it would be safer or more convenient if there was an option allowing to:
A: keep /directory1/ from any modifications and remove/replace  duplicates from /directory2/ only; or 
B: simply don't count duplicates _within the same tree_ at all, only between different trees. 
Perhaps (B) is better, as it could be used instead of (A) by running twice - 1st pass without this option pruning the directories that don't need to be preserved, then the 2nd pass with "between directories only" option and the one which should be treated as read-only in the first directory argument, to have it always counted as the "original" instance.
Especially since rdfind already discerns "DUPTYPE_WITHIN_SAME_TREE" vs. "DUPTYPE_OUTSIDE_TREE".

**Comment by pauldreik** [comment]
I agree this could be useful! However, it would bring complexity to the tool. Complexity increases the possibility for bugs. I do not like bugs. In this case, I do not think the added value is worth the cost.

**Comment by kolonuk** [comment]
After running this and inspecting the -dryrun output, I noticed that rdfind compares within the first directory, as well as between other directories specified on the command line.

I was only expecting it to compare between the directories, and not check EVERY file it found, regardless of directory.  Perhaps this could be mentioned in the man page?
