### ISSUE TITLE
Ability to filter file names with a regex

### ISSUE THREAD

**Issue by icefo** [pauldreik/rdfind#44]
Hello,

I need to deduplicate a huge mail folder from a mail server and some files are identical in a lot of mailboxes but they should not be hardlinked. I looked at the source code and I look quite easy to filter the list of files with a regex.

Would you consider merging those changes ? If you do I can implement that carefully and make a merge request but if you don't I just make the change I need quick & dirty

I just saw the issue about filtering the answer by file name. So I guess the answer is probably no

**Comment by pauldreik** [comment]
Thank you for your offer! As you guessed, I am afraid of introducing more complexity. Thanks anyway for reaching out.
