### ISSUE TITLE
Option to Omit a Directory or File

### ISSUE THREAD

**Issue by antonyupward** [pauldreik/rdfind#46]
Provide the ability to tell rdfind not to parse part of a tree...

e.g. rdfind -makehardlinks true "/usr/me" -omit "/usr/me/somedirectory"

In my use-case I have a directory with 30 sub-directories... and I need to run rdfind across 29 of the 30.

**Comment by pauldreik** [comment]
I agree it could be useful, but it adds a lot of complexity. For your case, may I suggest using  something like:
```sh
find /usr -mindepth 1 -maxdepth 1 -not -name sbin -print0 |xargs -0 rdfind
```
