### ISSUE TITLE
apt installs version 1.3.5 - which includes "failed to make symlink" error 

### ISSUE THREAD

**Issue by lefsky** [pauldreik/rdfind#47]
I just ran your program on a 10 Tb backup I made to try to reduce the overall size. Surprised to find that the "failed to make symlink error" hasn't been fixed in the version that apt installs. Seems like something that should be passed to all the automatic installation services....

**Comment by pauldreik** [comment]
If it is apt, I assume you use Debian or Ubuntu which are usually quick to pick up new versions. But once released, only security bugs are fixed. This is a "normal bug", so it probably won't warrant an update in old Debian/Ubuntu releases.
