### ISSUE TITLE
NTFS support

### ISSUE THREAD

**Issue by codingthat** [pauldreik/rdfind#53]
It's not clear what happens if you run this on an NTFS volume mounted from Linux.  Will NTFS hard links be created?

**Comment by pauldreik** [comment]
I do not know. I think there are multiple ways to mount an ntfs (fuse or kernel?) so I guess the answer depends on which one is used.

**Comment by charlesgerbra** [comment]
I have a partial answer. I have an NTFS file system I use in linux and windows. Mounted in linux with fuse, rdfind replaced some duplicate files with hard links.

**Comment by charlesgerbra** [comment]
linux symlinks: In an NTFS filesystem mounted on linux with fuse, the following command replaced all duplicate files it found with linux symlinks to the original file; linux reads the symlinks correctly, but windows doesn't. Windows interprets linux symlinks as text files, not links. This is expected, as windows knows nothing about linux symlinks. Actually, I have had mixed outcomes in windows with linux symlinks created with `ln -s`, with rdfind, and with other methods: sometimes windows fails to list the files with dir or File Explorer; other times it lists them but, as expected, opens them as text files. I don't know why the outcomes differ. This isn't the place to discuss it, as this is about rdfind, and symlinks are only mentioned in passing.

`rdfind -makesymlinks true targetdirectory`

**Comment by pauldreik** [comment]
Thanks for finding this out!
