### ISSUE TITLE
add travis builds

### ISSUE THREAD

**Issue by pauldreik** [pauldreik/rdfind#6]

**Comment by pauldreik** [comment]
There are now two builds on Travis, one with gcc 4.8(?) and clang (3.4?). This keeps the project working even on older platforms (Ubuntu 14.04).

It would be good to add mac os x builds as well, but that probably needs fiddling with homebrew or macports to get nettle and gnu tools installed. Maybe some Mac user wants to provide the travis config that makes that work?

**Comment by djhejna** [comment]
When running configure on Ubuntu 14.04 the following error is reported:
checking for stat... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
./configure2: line 4230: syntax error near unexpected token `11,noext,mandatory'
./configure2: line 4230: `      AX_CXX_COMPILE_STDCXX(11,noext,mandatory) }'

Which appears to originate in configure.ac (lines 73/74).

**Comment by pauldreik** [comment]
I do not have a 14.04 to test with, but what happens if you do like the travis build does?
https://github.com/pauldreik/rdfind/blob/909e90f974ec1248fce6be71e71722e559745445/.travis.yml#L24

**Comment by pauldreik** [comment]
This discussion continued over here: https://github.com/pauldreik/rdfind/issues/19
