### ISSUE TITLE
Flag to Ask/Prompt before removing

### ISSUE THREAD

**Issue by xeruf** [pauldreik/rdfind#65]
I would like to have a mode where I have to confirm each deletion. Right now I go through the file and manually compose a rm command, which is rather tedious.

Also, how about a way to read the results back in, if a huge chunk has been scanned?

**Comment by pauldreik** [comment]
Sorry for the late reply.

I do not want to make the tool interactive.

Regarding your second request, that would complicate the program too much for the benefit.
