### ISSUE TITLE
Set default hash to SHA1. Add support for SHA256

### ISSUE THREAD

**Issue by pauldreik** [pauldreik/rdfind#7]
This is suggested by Debian bug [815120](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815120)
and a good idea.

**Comment by pauldreik** [comment]
This is now implemented. Thanks Dmitry Smirnov for bringing up the issue!

**Comment by pauldreik** [comment]
Sha1 was selected as the default over sha256, because of the performance penalty. This may change at a later stage. See the commit message in b682e60037478c74a2dec1f03a023df0263d9cdf

**Comment by pauldreik** [comment]
This is in 1.4.0-alpha0

**Comment by baryluk** [comment]
Ok, MD5 should die.

FYI modern CPUs (Intel, AMD, IBM, ARM) do have hardware acceleration for SHA1 and SHA256. Not every crypto library supports that tho.

Thanks.
