### ISSUE TITLE
Please do a release

### ISSUE THREAD

**Issue by magnetophon** [pauldreik/rdfind#72]
I noticed there have been some bugfixes [since the last release](https://github.com/pauldreik/rdfind/compare/releases/1.4.1...master).

Could you do another release for the benefit of us distro packagers?
Thanks!

**Comment by pauldreik** [comment]
Sorry for not replying earlier. There is really mostly maintenance work done, the only new feature is the maxsize option. I will try to make a release soon.

**Comment by pauldreik** [comment]
Which distro are you packaging for?
Is there anything else you want me to change to make packaging easier?

**Comment by magnetophon** [comment]
All good.
I'm packaging for NixOS, and as far as I remamber everything was easy-peasy.

Thanks!

**Comment by pauldreik** [comment]
I just made a 1.5.0 release.

**Comment by magnetophon** [comment]
Thanks!

**Comment by magnetophon** [comment]
NixOS PR merged: https://github.com/NixOS/nixpkgs/pull/136764
Thanks again!
