### ISSUE TITLE
Failed moving to a temporary file

### ISSUE THREAD

**Issue by sdorof1** [pauldreik/rdfind#86]
I try to use `rdfind` to compress my backups with replacement the duplicates by hardlinks. But I get lots of error messages like this:

`Failed moving /mnt/arxiv/BACKUP/backintime/b586/sd/1/20181231-000001-573/backup/home/sd/sources/maven-example-en/html/images/callouts/27.svg to a temporary file`

And no hardlinks have been created.

**Comment by pauldreik** [comment]
Is the mount point writable?

**Comment by sdorof1** [comment]
> Is the mount point writable?

oh, yes, this was the point, thanks.
