### ISSUE TITLE
 error: ‘numeric_limits’ is not a member of ‘std’

### ISSUE THREAD

**Issue by mids33** [pauldreik/rdfind#87]
compiling under cygwin and rdfind 1.5

================================================================
$ make
make  all-am
make[1]: Entering directory '/cygdrive/e/lab/rdfind'
g++ -DHAVE_CONFIG_H -I.     -g -O2 -MT rdfind.o -MD -MP -MF .deps/rdfind.Tpo -c -o rdfind.o rdfind.cc
rdfind.cc: In function ‘Options parseOptions(Parser&)’:
rdfind.cc:224:30: error: ‘numeric_limits’ is not a member of ‘std’
  224 |     o.maximumfilesize = std::numeric_limits<decltype(o.maximumfilesize)>::max();
      |                              ^~~~~~~~~~~~~~
rdfind.cc:224:45: error: expected primary-expression before ‘decltype’
  224 |     o.maximumfilesize = std::numeric_limits<decltype(o.maximumfilesize)>::max();
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:656: rdfind.o] Error 1
make[1]: Leaving directory '/cygdrive/e/lab/rdfind'
make: *** [Makefile:535: all] Error 2
===================================================================
now editing  rdfind.cc
and add #include <limits> 
it compile and run ..
did it break something doing this ?

**Comment by pauldreik** [comment]
This was fixed on the devel branch, see https://github.com/pauldreik/rdfind/commit/61877de88d782b63b17458a61fcc078391499b29

**Comment by pauldreik** [comment]
now on the main branch as well.
