### ISSUE TITLE
Add Mac OS X support to travis builds

### ISSUE THREAD

**Issue by pauldreik** [pauldreik/rdfind#9]
Any Mac users? I would be happy if someone could help me adding mac builds to travis.

There is probably quite a lot of "gnu-isms" in the shell scripts etc which may be a problem.

**Comment by pompomtom** [comment]
Hiya,

Mac user here (can bash, some C++ from Arduino etc). I love this tool, and hope I could be of some help. 

Unfortunately I have just learned of travis by reading this. So it's a CI build/test thing? I think I might be of use.

What do you need?

**Comment by pauldreik** [comment]
Hi, thanks for volunteering!
There are already two flavours of CI builds for linux:
- travis, which runs a basic build+unit tests with two compilers. See https://github.com/pauldreik/rdfind/blob/master/.travis.yml for details.
- appveyour, which runs the comprehensive test script for trying out various combinations of build flags, compilers etc. See https://github.com/pauldreik/rdfind/blob/master/appveyor.yml

These two test builds are great for the quality of the project. What I would like from a mac build is first and foremost just a check that it compiles. Bonus points for also running the unit tests.

I believe travis supports mac builds, but appveyour doesn't.

I think the easiest and most practical way forward is if you fork this repo on github, then enable travis for your fork. You can disable the linux builds to speed it up, and make as many test commits you like (they tend to be many when trouble shooting build systems:-). Once you have something running, you can either send me a patch or make a minimal pull request and we'll take it from there.

It will be interesting to see how it goes, good luck!

**Comment by pauldreik** [comment]
I added a github action which builds on mac os x. It does not run the tests due to the readlink -f flag not being supported on mac.
