### ISSUE TITLE
Fix 'See Also' sources on the 'man page'

### ISSUE THREAD

**Issue by I-Knight-I** [pauldreik/rdfind#90]
![image](https://user-images.githubusercontent.com/26165117/138270407-74dcd0fb-64f2-4447-929c-db97ea47c769.png)

All the links provided as sources in the footnotes are broken and return a 404. Fix would be appreciated; particularly for the Symlinks one since the wording is a little confusing and I'm unable to find the exact reference with a (very quick) Google search.

Maybe a QoL improvement too: make the '(numbers)' an actual hyperlink instead of a footnote reference. Or display the number as superscript to provide extra clarity.

**Comment by pauldreik** [comment]
thanks, these are inserted by man2html. I took the easy route and removed the section numbers which makes man2html not convert them to links. will be on the main branch soon.

you could probably just use "man md5sum" on your system to see the man page.
